name: Generate documents

on:
  push:
    branches: [ main ]

jobs:
  docs:
    name: Generate documents
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generating documents
        uses: obaland/panvimdoc@main
        with:
          vimdoc: vfiler
          description: File manager plugin for Vim/Neovim
          pandoc: doc/vfiler.md
          toc: true
      - name: Commit changes
        env:
          COMMIT_MSG: |
            docs: update doc/vfiler.txt
            skip-checks: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add doc/vfiler.txt
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push)
