name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install -y luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: sudo make lint
  
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua/
